version: "3.7"

services:
  login_app:
    container_name: test_login_app
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: run
    volumes:
      - .:/app/
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - 8001:8001
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_login
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data


volumes:
  postgres-data: